language: php

env:
  - NETTE=nette-2.1
  - NETTE=default # 2.2
  - NETTE=nette-dev

php:
  - 5.4
  - 5.5
  - 5.6




before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev


script: ./vendor/bin/tester tests

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
